### ISSUE TITLE
Tinkering Error

### ISSUE THREAD

**Issue by neoOpus** [littlewhitecloud/win32material#1]
Hi,

I attempted to conduct some experiments with this, but unfortunately, I am unable to make it function properly. Is there something I am missing?
```python
__init__.py", line 6, in <module>
    from .win32material import ApplyAcrylic, ApplyMica, ApplyBlur
ImportError: attempted relative import with no known parent package
```

**Comment by littlewhitecloud** [comment]
@neoOpus Thanks for checking out this repo! Please tell me how do you import this package?
If you just run the `__init__.py` please write down this to call the package.
```python
from win32material import ... # Function you want to call
```

**Comment by neoOpus** [comment]
Thank you for your prompt reply and sorry about the delay.

Actually I am impressed by your age and how interesting your projects are, thus said.

I think your _init_.py has an error, an extra dot before win32marterial
`from .win32material import ApplyAcrylic, ApplyMica, ApplyBlur
`

It should be 
`from win32material import ApplyAcrylic, ApplyMica, ApplyBlur
`

I am not proficient in programming, so it is highly likely that you have much more knowledge in this area so don't hesitate to correct me.

**Comment by littlewhitecloud** [comment]
Actually, that's not an error, please read https://docs.python.org/3/tutorial/modules.html#intra-package-references

**Comment by littlewhitecloud** [comment]
This issue will be closed if there are no other issues.

**Comment by littlewhitecloud** [comment]
> Thank you for your prompt reply and sorry about the delay.
> 
> Actually I am impressed by your age and how interesting your projects are, thus said.
> 
> I think your _init_.py has an error, an extra dot before win32marterial `from .win32material import ApplyAcrylic, ApplyMica, ApplyBlur `
> 
> It should be `from win32material import ApplyAcrylic, ApplyMica, ApplyBlur `
> 
> I am not proficient in programming, so it is highly likely that you have much more knowledge in this area so don't hesitate to correct me.

@neoOpus Actually, that's not an error, please read https://docs.python.org/3/tutorial/modules.html#intra-package-references

Please follow these steps:
Run this command in your terminal
```console 
pip install win32material
```
Write down:
```python
from tkinter import Tk
from win32material import ApplyMica
from ctypes import windll, c_char_p

example = Tk() # Create a Tk window
example.geometry("1165x605") # Set the size of the window
example.title("Example") # Set the title of the window

# Without this line, the FindWindowW can't find the hwnd correctly
example.iconbitmap("") # Set the icon of the window

example["background"] = "black"
ApplyMica(windll.user32.FindWindowW(c_char_p(None), "Example"), True, True)

example.mainloop() # Window mainloop
```
At last, save and run this file, you will see the window with mica effect without ImportError.

![image](https://github.com/littlewhitecloud/win32material/assets/71159641/3c977aa0-30ac-4eb7-93ee-5678f299805c)
