### ISSUE TITLE
这个项目的作者竟然忘记将最新版本上传到 PyPI 了！

### ISSUE THREAD

**Issue by Xiaokang2022** [littlewhitecloud/win32material#3]
请问作者是否忘记将 `1.0.4` 版本上传到 **PyPI** 了？

**PyPI** 上该项目的最新版本是 `1.0.3`，而该版本在 **Windows 11** 操作系统中会引发异常，其原因是 *\_\_init\_\_.py* 文件中对操作系统的判断错误导致的。

希望作者可以尽快将 `1.0.4` 版本上传到 **PyPI**，非常感谢！~~（不然我不方便使用此项目）~~

**Comment by littlewhitecloud** [comment]
> 请问作者是否忘记将 `1.0.4` 版本上传到 **PyPI** 了？
> 
> **PyPI** 上该项目的最新版本是 `1.0.3`，而该版本在 **Windows 11** 操作系统中会引发异常，其原因是 ___init__.py_ 文件中对操作系统的判断错误导致的。
> 
> 希望作者可以尽快将 `1.0.4` 版本上传到 **PyPI**，非常感谢！~（不然我不方便使用此项目）~

~~好的好的好的，我忘记了~~

搞笑了，我后悔重命名了
后来是上传没有成功
感谢提醒
