### ISSUE TITLE
Recognition to original repo

### ISSUE THREAD

**Issue by marticliment** [littlewhitecloud/win32material#5]
(Disclaimer, I am the win32mica maintainer)

It is obvious that an important part of the module has been written by you, but it is also obvious that this module is an improved fork from win32mica.

It would be nice to add a little bit of recognition on the footer of the readme, even if the MIT license doesn't strictly require so :)

What do you think?

**Comment by littlewhitecloud** [comment]
> (Disclaimer, I am the win32mica maintainer)
> 
> It is obvious that an important part of the module has been written by you, but it is also obvious that this module is an improved fork from win32mica.
> 
> It would be nice to add a little bit of recognition on the footer of the readme, even if the MIT license doesn't strictly require so :)
> 
> What do you think?

Sorry for waiting, I didn't check the repo for a time.
I will write the recogntiton in the readme and add the links in the code!

**Comment by marticliment** [comment]
Don't worry, and thanks!
